In [1]:
import pandas as pd

data = pd.read_csv("data/creditcard.csv")

data.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-6.677212,5.529299,-7.193275,6.081321,-1.636071,0.500610,-4.640770,-4.339840,-0.950036,0.566680,...,5.563301,-1.608272,0.965322,0.163718,0.047531,0.466165,0.278547,1.471988,105.89,1
1,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,-3.232153,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
2,-4.446847,-0.014793,-5.126307,6.945130,5.269255,-4.297177,-2.591242,0.342671,-3.880663,-3.976525,...,0.247913,-0.049586,-0.226017,-0.401236,0.856124,0.661272,0.492560,0.971834,1.00,1
3,-1.309441,1.786495,-1.371070,1.214335,-0.336642,-1.390120,-1.709109,0.667748,-1.699809,-3.843911,...,0.533521,-0.022180,-0.299556,-0.226416,0.364360,-0.475102,0.571426,0.293426,1.00,1
4,0.206075,1.387360,-1.045287,4.228686,-1.647549,-0.180897,-2.943678,0.859156,-1.181743,-3.096504,...,0.469199,0.344930,-0.203799,0.376640,0.715485,0.226003,0.628545,0.319918,0.76,1

In [3]:
df_class_0 = data[data['Class'] == 0]
df_class_1 = data[data['Class'] == 1]

In [7]:
df_class_0_sample = df_class_0.sample(frac=0.3)

In [13]:
df_class_1_sample = df_class_1.sample(len(df_class_0_sample), replace = True)

In [15]:
data_balanced = pd.concat([df_class_0_sample, df_class_1_sample], axis=0).sample(frac=1)

In [16]:
data_balanced

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
12738,-3.434963,3.359181,-2.570848,-1.536103,-0.247698,-0.106212,-0.346056,1.513991,1.393054,2.475764,...,-0.497222,-1.017725,0.230810,-0.410804,0.271676,0.209861,0.993478,0.620606,8.95,0
28346,-0.340490,1.611546,1.928291,4.424937,-0.007085,0.937247,0.068213,0.197343,-1.359460,1.838634,...,0.274802,1.255174,-0.157210,0.042957,-0.584905,0.505676,0.623325,0.333714,12.31,0
2,-4.446847,-0.014793,-5.126307,6.945130,5.269255,-4.297177,-2.591242,0.342671,-3.880663,-3.976525,...,0.247913,-0.049586,-0.226017,-0.401236,0.856124,0.661272,0.492560,0.971834,1.00,1
18,0.469750,-1.237555,-1.767341,4.833490,-0.268715,-0.512760,1.140149,-0.341273,-1.046351,0.085662,...,0.303905,-0.647075,-0.373014,0.260801,-0.496566,-0.245973,-0.117858,0.144774,723.21,1
5,-0.734303,0.435519,-0.530866,-0.471120,0.643214,0.713832,-1.234572,-2.551412,-2.057724,0.166831,...,-1.004877,1.150354,-0.152555,-1.386745,0.004716,0.219146,-0.058257,0.158048,29.95,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,-0.734303,0.435519,-0.530866,-0.471120,0.643214,0.713832,-1.234572,-2.551412,-2.057724,0.166831,...,-1.004877,1.150354,-0.152555,-1.386745,0.004716,0.219146,-0.058257,0.158048,29.95,1
12751,2.282621,-0.786155,-1.878902,-1.227970,0.084491,-0.320437,-0.397621,-0.132244,-0.497565,0.995503,...,-0.025838,-0.094976,0.026976,-1.402093,0.109333,-0.209937,-0.050920,-0.090148,7.19,0
6560,-0.436954,0.386406,-0.097900,-1.938958,2.762562,3.795997,0.224716,0.884427,0.281618,-1.400584,...,-0.236326,-0.630548,-0.023894,0.567200,-0.305573,-0.284865,-0.024112,-0.062892,38.52,0
16052,2.180383,-0.511943,-2.032060,-0.560082,0.144556,-0.845554,0.141327,-0.339407,-1.140480,1.123591,...,-0.213894,-0.037038,0.076059,0.809459,0.220874,0.772370,-0.106748,-0.083118,12.50,0
29,-2.628922,2.275636,-3.745369,1.226948,-1.132966,-1.256353,-1.752420,0.281736,-1.792343,-4.820779,...,0.870730,1.269473,-0.265494,-0.480549,0.169665,0.096081,0.070036,0.063768,144.62,1

In [17]:
target = 'Class'
features = list(data_balanced.columns)
features.remove(target)

X = data_balanced[features]
y = data_balanced[target]

In [21]:
from sklearn.metrics import recall_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import precision_recall_curve
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=2000)

In [22]:
data_balanced['prob_ok'], data_balanced['prob_fraud'] = cross_val_predict(model,
                                                   X,
                                                   y,
                                                   method = "predict_proba").T

precision, recall, thresold = precision_recall_curve(y, data_balanced['prob_fraud'])

In [23]:
scores = pd.DataFrame({"thresold":thresold,
                       "precision":precision[:-1],
                       "recall":recall[:-1]})

scores

     thresold  precision    recall
0    0.795087   0.993825  1.000000
1    0.796782   0.993801  0.996131
2    0.808789   0.993917  0.996131
3    0.811688   0.993897  0.992849
4    0.814355   0.994014  0.992849
..        ...        ...       ...
247  1.000000   0.998849  0.203517
248  1.000000   0.998828  0.199883
249  1.000000   0.998792  0.193787
250  1.000000   0.998768  0.190035
251  1.000000   0.998683  0.177843

[252 rows x 3 columns]

In [24]:
new_threshold = scores[scores['recall'] >= 0.9].thresold.max()
new_threshold

0.9903380051877759